# Generated by Django 4.0 on 2022-01-05 01:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makername', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ('makername',),
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('nome', models.CharField(max_length=200)),
                ('bi', models.CharField(max_length=200, unique=True)),
                ('NIF', models.CharField(max_length=200, unique=True)),
                ('morada', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enfermeiro',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.utilizador')),
                ('especialidade', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nome',),
            },
            bases=('hospital.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.utilizador')),
            ],
            options={
                'ordering': ('nome',),
            },
            bases=('hospital.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.utilizador')),
                ('especialidade', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('nome',),
            },
            bases=('hospital.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.utilizador')),
            ],
            options={
                'ordering': ('nome',),
            },
            bases=('hospital.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Outro_Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artigo', models.CharField(max_length=200)),
                ('nome_artigo', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('titular_AIM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dci', models.CharField(max_length=200)),
                ('nome_medicamento', models.CharField(max_length=200)),
                ('forma_farmaceutica', models.CharField(max_length=100)),
                ('dosagem', models.CharField(max_length=200)),
                ('estado_autorizacao', models.BooleanField()),
                ('generico', models.BooleanField()),
                ('slug', models.CharField(max_length=200)),
                ('titular_AIM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Ato_Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now=True)),
                ('quant_med', models.CharField(max_length=200)),
                ('quant_art', models.CharField(max_length=200)),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.medicamento')),
                ('outro_artigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.outro_artigo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medico')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.utente')),
            ],
            options={
                'ordering': ('hora',),
            },
        ),
        migrations.CreateModel(
            name='Ato_Farmaceutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now=True)),
                ('quant_med', models.CharField(max_length=200)),
                ('quant_art', models.CharField(max_length=200)),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.medicamento')),
                ('outro_artigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.outro_artigo')),
                ('farmaceutico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.farmaceutico')),
            ],
        ),
        migrations.CreateModel(
            name='Ato_Enfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now=True)),
                ('quant_med', models.CharField(max_length=200)),
                ('quant_art', models.CharField(max_length=200)),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.medicamento')),
                ('outro_artigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.outro_artigo')),
                ('enfermeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.enfermeiro')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.utente')),
            ],
        ),
    ]
